name: Create Docker image on new release

on:
  release:
    types: [published]

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get latest airdcpp release
        id: airdcpp-release
        run: |
          release_version=$(curl -sL https://api.github.com/repos/airdcpp-web/airdcpp-webclient/releases/latest | jq -r ".tag_name")
          echo ::set-output name=num_rels_found::$(curl -s "https://hub.docker.com/v2/repositories/valmati/airdcpp-webclient/tags/?page_size=10&ordering=last_updated" | jq '.results[].name' | grep -c "${release_version}")
          echo ::set-output name=release_tag::${release_version}
      -
        if: ${{ steps.airdcpp-release.outputs.num_rels_found == 0 }}
        name: Checkout
        uses: actions/checkout@v2
      -
        if: ${{ steps.airdcpp-release.outputs.num_rels_found == 0 }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        if: ${{ steps.airdcpp-release.outputs.num_rels_found == 0 }}
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: valmati
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: ${{ steps.airdcpp-release.outputs.num_rels_found == 0 }}
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          platforms: linux/arm/v7
          push: true
          tags: |
            valmati/airdcpp-webclient:latest
            valmati/airdcpp-webclient:${{ steps.airdcpp-release.outputs.release_tag }}
